- name: This playbook demonstrates invoking our custom nginx role
  hosts: all 
  become: yes
  tasks:
  - name: Install nginx
    apt: name=nginx,curl state=latest update_cache=yes

  - name: Start the nginx
    service: name=nginx enabled=true state=started
