- name: Check if nginx is already running in Rocky
  shell: curl localhost
  register: output
  ignore_errors: yes

- debug: var=output

- name: Start nginx server in Rocky 
  when: ( output.rc !=0 )
  shell: nginx 
