#!/usr/bin/env groovy

pipeline {
    agent {
        label 'built-in'
    }
    stages {
        stage('Build Custom Docker Image') {
            steps {
                script {
		    dir("Day5/CustomDockerAnsibleNodeImages/ubuntu-ansible") {
		         sh "cp ~/.ssh/id_ed25519.pub authorized_keys"
		         sh "docker build -t tektutor/ubuntu-ansible:1.0 ."
			 sh "rm authorized_keys"
			 sh "docker images"
		    }
                }
            }
        }
	stage("Invoke Terraform") {
		steps {
			timeout( time: 5, unit: "Minutes") {
			   input message: 'Are we good to perform infrastructure automation ?', ok: 'Yes'
			}
			echo "About to invoke Terraform ..."
		}
	}
        stage('Invoke Terraform Automation Script') {
            steps {
                script {
		  dir("Day5/invoking-ansibleplaybook-from-terraform") {
                    sh "terraform init"
		    sh "terraform apply --auto-approve"
		  }
                }
            }
        }
        stage('Invoke Ansible Playbook') {
            steps {
                script {
		  dir("Day5/invoking-ansibleplaybook-from-terraform") {
                    sh "ansible-playbook -i hosts install-nginx-playbook.yml"
		  }
                }
            }
        }
        stage('Test if we are able to access web page from provisioned container') {
            steps {
                script {
                    sh "curl http://localhost:8001"
                }
            }
        }
    }
    }
}
